### ISSUE TITLE
Gateway error scenarios

### ISSUE THREAD

**Issue by andrew-coleman** [hyperledger/fabric-gateway#178]
Add extra scenario tests to the suite that specifically test the error messages returned from Fabric Gateway.
Ensure relevant messages are easily accessible and contain appropriate diagnostic information.
Ensure consistency across the three SDKs.

**Comment by bestbeforetoday** [comment]
For a production-ready client application, we need to be able to distinguish whether a given error is:
1. a connection failure that can be retried
2. an unrecoverable failure (like bad credentials, channel name, chaincode name or transaction name)
3. a valid application-level error from chaincode (like querying an asset that doesn’t exist)

We might be able to achieve this with good use of [gRPC status codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) on errors returned from the Gateway peer. We will need to document status codes we use and their meaning. This documentation might need to include code examples demonstrating how to capture errors / exceptions and examine the status codes.

**Comment by denyeart** [comment]
Done!
