### ISSUE TITLE
Intermitted private data scenario test failure

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#182]
The following error is fairly common in builds:
```
Scenario: Org1 writes private data to SharedCollection, endorsed by Org3, and can read it back via Org1 peer # /home/vsts/work/1/s/scenario/features/privatedata.feature:78
  Then the response should be "value-105" # /home/vsts/work/1/s/scenario/features/privatedata.feature:91
    Error: transaction response "" does not match expected value "value-105"
```

This instance of the error occurred in the Go scenario tests, but I think they have happened intermittently in other language scenario tests.

**Comment by andrew-coleman** [comment]
This is probably just an unrealistic test.  It submits in one org, then immediately tries to read it from another.  The transaction probably hasn’t committed on that other org’s peer in this case.  In reality, the client would either specify the same org as for the submit transaction, or would leave the gateway to choose one based on block height.

I'll remove this test.
