### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#209]
A release process (ideally automated in the CI pipeline) needs to be implemented and documented for all of the client language APIs. This includes:

- Selecting specific builds (or Git commits) as releases and specifying their release version.
- Publishing of release builds (to NPM registry, Maven Central etc.)
- Creating GitHub releases and associated Git tags.

**Comment by bestbeforetoday** [comment]
We need to be careful to use the lowest supported runtime version when building published packages. For example, Java 8 should be used explicitly rather than the default Java version in the build system (which I think is Java 11) since bytecode generated by later compilers may not be runnable by earlier JVM versions.

**Comment by jt-nti** [comment]
@denyeart the [gateway node SDK is already being published](https://www.npmjs.com/package/fabric-gateway) without the `@hyperledger` namespace- are all the hyperledger node modules moving?

**Comment by jt-nti** [comment]
Discussed with @denyeart and from a TSC perspective, the recommendation is that all hyperledger projects should use the hyperledger scope

The existing `fabric-gateway` module will be deprecated and a new `@hyperledger/fabric-gateway` module published instead. There are very few existing users from the beta who will need to update their code, and hopefully having a deprecated module in the global namespace won't cause too much confusion for new users 🤞

For all Gateway SDKs, the plan is to release at version 1.0.0 and follow the Go versioning guidelines, i.e. stay at version 1.x.x keeping API changes compatible for as long as possible, only moving to a new major version if breaking API changes cannot be avoided

Mixing different language SDKs in the same repo means that the Go module includes the other SDKs, which is not ideal. I explored the possibility of releasing version 1.0.0 from a `v1` directory, i.e. `github.com/hyperledger/fabric-gateway/v1`, however this makes the repository even more unusual from a Go module perspective, and the unrelated content would still be downloaded anyway. Leaving the Go module at the top-level is preferred until reaching a major version change

**Comment by bestbeforetoday** [comment]
This Maven plugin looks like it might be useful for automating staging/release to Maven Central: https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin

**Comment by jt-nti** [comment]
Being able to [sync the Hyperledger artifactory](https://central.sonatype.org/publish/large-orgs/) with Maven Central looks like it would be really nice if it's possible, but the staging plugin looks like a good potential interim solution, thanks.

**Comment by jt-nti** [comment]
Note to self: need to update github pages once the release is released! https://hyperledger.github.io/fabric-gateway/
