### ISSUE TITLE
good practice for gateway peer loadbalancing

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#257]
We should provide guidance on this as part of samples/documentation some considerations are
- load balancers in a K8s environment
- client handling the balancing itself

Please feel free to add more thoughts, info for capturing plus where appropriate artifacts demonstrating this should be created
- eg samples, docs

**Comment by davidkel** [comment]
@mbwhite @jkneubuh This might be a good place to capture any relevant info

**Comment by jkneubuh** [comment]
On the Kubernetes front there are a few different approaches that we can employ to shape traffic between the gateway client and peers.  All of these will provide some level of HA, failover, and traffic distribution across a set of peers.

Gateway load balancing within Kubernetes can be accomplished by establishing a `Service` instance matching node selectors for multiple peer `Deployments`.  Provided that the TLS certificates for the peers have been initialized with a common SAN in the signing request, a single k8s Service can act as a front-end to multiple peers using a common DNS name.  When establishing a TCP connection from the client to the gateway peer, Kubernetes will use the Service interface to dynamically resolve the address of one of the Pods bound to the Service.

One downside of using the [Kubernetes Service routing](https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies) is that any finer-grain message routing, e.g. at the gRPC message layer, is not possible.  Kubernetes can help with the initial assignment of a TCP connection to one of the backing peers, but once a client connection is established it will be maintained for the duration of the socket.

By default a Kubernetes Service will use `iptables` to bind a client connection to a peer pod using random assignment.  The pods backing a Service instance can be monitored via Readiness Probes, ensuring that only "ready" services receive gRPC handshakes from the gateway client SDK.

Building on the iptables routing, it looks like a Kube service can also use `IPVS` mode to further shape the IP resolution:

> IPVS provides more options for balancing traffic to backend Pods; these are:

rr: round-robin
lc: least connection (smallest number of open connections)
dh: destination hashing
sh: source hashing
sed: shortest expected delay
nq: never queue

In addition, the IPVS routing mode includes a `sessionAffinity` attribute which can be set to "ClientIP", ensuring that connections from a particular client are resolved to the same peer pod.

Building on the Kubernetes defaults, we could consider an additional layer of traffic shaping by co-deploying a Fabric network within a _service mesh_, as provided by Ambassador, Istio, or Linkerd.  This approach may be a little more involved and not generally applicable to all environments running a Fabric network on K8s.

In addition to finding a home on the Fabric docs site, I like the idea of including a reference deployment within the Kubernetes test network.  Do we have a reference example app showing the best practices for authoring a Fabric application using the Gateway SDK?  (e.g. fabric-rest-sample, but using the Gateway SDK)

**Comment by mbwhite** [comment]
@jkneubuh I can create a PR on the `test-network-k8s` that includes the changes along these lines.  Ironically they are relatively minor changes, but I guess that shows the power of K8S.

I believe there is an example planned for the gateway, meanwhile I'll refer you to the LedgerMessaging IBM example.

**Comment by bestbeforetoday** [comment]
@mbwhite @jkneubuh Have we done all we need (or realistically plan to do for now) on this issue? If so, I'll close it. If not, what needs doing and what's the outlook on that?

**Comment by mbwhite** [comment]
@bestbeforetoday I believe we've done all we can at the moment.

**Comment by jkneubuh** [comment]
I still have a draft PR (lingering) open for the peer load balancing in k8s.  It's got some good info but is still too "kube specific" in the context where it's currently anchored in the docs.

Mark please leave this one open.  I will connect with Josh (H) on finding the correct page / site for the doc content.

**Comment by bestbeforetoday** [comment]
Another potentially useful snippet of information on how to configure client-side load balancing over a set of IP addresses using the Node gRPC client: https://github.com/grpc/grpc-node/issues/1307#issuecomment-601312421

**Comment by bestbeforetoday** [comment]
Best-practice recommendations for production deployment, which discusses load balancing / fail-over, is published in the [full-stack-asset-transfer-guide](https://github.com/hyperledger/fabric-samples/blob/124adb43f964c4ef62836c547bba851a4d10bfb3/full-stack-asset-transfer-guide/docs/ApplicationDev/01-FabricGateway.md#production-deployment-of-fabric-gateway) sample.
