### ISSUE TITLE
No automatic recovery for chaincode events when the gateway peer restarts

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#261]
A client application performing submits and evaluates will automatically recover (ie the client doesn't have to do anything special such as recreating connections/gateways/getting networks/getting contracts). The client can continue to retry submission and evaluation until the gateway peer comes back up and then they will be processed as normal.

This is not the case for listening for chaincode events. If the peer gateway goes down then the event sink becomes unusable and must be closed. This pattern is reflected in the sample code
```
const events = await network.getChaincodeEvents(chaincodeName, { startBlock: BigInt(101) });
try {
    for async (const event of events) {
        // Process event
    }
} finally {
    events.close();
}
```

As the reasoning behind this is not explicit this understanding may not be realised so I think this needs to be clarified in the documentation (also note that although for async is the preferred way to handle async iterators, users may still opt to use it a different way).

Automatic recovery should be documented as the client app's responsibility and we should have a sample that demonstrates this (Rest Sample comes to mind)

This issue is only a documentation issue, but maybe a future capability for the gateway might be to have automatic recovery ?

Note this was only tested on node thin client, no testing of java or Go has been done

**Comment by denyeart** [comment]
Make sure it is clear in the API docs.

**Comment by bestbeforetoday** [comment]
I _think_ we can claim completion on this now that the v1.1 release contains checkpointing and fabric-samples ([off_chain_data](https://github.com/hyperledger/fabric-samples/tree/main/off_chain_data)) and example code in the [API documentation](https://hyperledger.github.io/fabric-gateway/main/api/node/interfaces/Network.html) demonstrate how it is used to resume listening after a connection or gateway peer outage.
