### ISSUE TITLE
When gateway peer starts or restarts it could be unusable

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#262]
As of driver downloaded today 22nd Oct 2021 (built 3 days ago)
hyperledger-fabric.jfrog.io/fabric-peer    cd4ffa294471        3 days ago          54.7MB

While testing bringing the gateway peer down and up I've found it to be unreliable when it comes back up, ie unable to submit transactions with 1 of 2 errors
```
14 UNAVAILABLE: failed to select a set of endorsers that satisfy the endorsement policy
```
and
```
14 UNAVAILABLE: no combination of peers can be derived which satisfy the endorsement policy: no peer combination can satisfy the endorsement policy
```
The gateway peer remains in this state (stopping and starting the client makes no difference). It requires another restart
One thing that appears to affect recovery is how much pressure the client is putting on the gateway peer during the time it comes up. If I reduce the pressure the gateway peer seems to restart more reliably .

**Comment by andrew-coleman** [comment]
Closing as resolved
