### ISSUE TITLE
Bringing down peers during evaluate returns unexpected errors to client

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#276]
I have a 3 org 2 peer network setup as follows
peer0.org1: chaincode installed
peer1.org1: no chaincode, gateway peer

peer0.org2: chaincode installed
peer1.org2: offline

peer0.org3: chaincode installed
peer1.org3: offline

When I start sending evaluate requests to the gateway, all is good and it chooses peer0.org1 as a peer to evaluate (all peers are at the same block height and in this test, it never changes)

If I stop peer0.org1 and peer0.org2 I see that the client receives 
```
{"component":"CLIENT","timestamp":"2021-11-02T12:48:38.249Z","txnId":"b2e4e99505a5f9ce5dee3a94bf4462e4b8514a119d9c331eaad6052d761524f9","stage":"Failed","message":"10 ABORTED: evaluate call to endorser returned an error response, see attached details for more info[{\"address\":\"peer0.org1.example.com:8051\",\"message\":\"error 500 returned from chaincode basic on channel mychannel: error in simulation: failed to execute transaction b2e4e99505a5f9ce5dee3a94bf4462e4b8514a119d9c331eaad6052d761524f9: error sending: chaincode stream terminated\",\"mspId\":\"Org1MSP\"}]"}
```
but it then briefly (I believe) moves to peer0.org2 and then reports errors again as that stops before finally using peer0.org3 successfully.

I was not expecting any errors to be reported as there was always 1 peer available that could be used to evaluate.

Note again that this is a graceful peer shutdown rather than a loss of connectivity or non graceful peer termination

**Comment by davidkel** [comment]
Repeating the same where I kill peers rathan terminate cleanly I get the same issue where I would not expect the client to get an error because there was at least one peer available that could evaluate, this time the error I get is
```
10 ABORTED: failed to evaluate transaction, see attached details for more info, Details: [{\"address\":\"peer0.org1.example.com:8051\",\"message\":\"rpc error: code = Unavailable desc = transport is closing\",\"mspId\":\"Org1MSP\"},{\"address\":\"peer0.org3.example.com:11051\",\"message\":\"rpc error: code = Unavailable desc = transport is closing\",\"mspId\":\"Org3MSP\"}]"
```

**Comment by sapthasurendran** [comment]
Retested the same scenario with new gateway version , Issue resolved . 
Client app did not receive any errors when  peers peer1.org2, peer1.org3 went offline. Evaluate transactions worked successfully with rest of the peers.
