### ISSUE TITLE
Enough information not available in fabric gateway error message

### ISSUE THREAD

**Issue by sapthasurendran** [hyperledger/fabric-gateway#278]
Long running transactions fails during endorsement phase with error message :

`10 ABORTED: failed to collect enough transaction endorsements, see attached details for more info Details: [{\"address\":\"peer0.org2.example.com:9051\",\"message\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\",\"mspId\":\"Org2MSP\"},{\"address\":\"peer1.org2.example.com:9151\",\"message\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\",\"mspId\":\"Org2MSP\"},{\"address\":\"peer0.org3.example.com:11051\",\"message\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\",\"mspId\":\"Org3MSP\"},{\"address\":\"peer1.org3.example.com:11151\",\"message\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\",\"mspId\":\"Org3MSP\"}]`

When I increase the `CORE_CHAINCODE_EXECUTETIMEOUT` time this error happens to go away . 

Details provided in the error message doesn't provide information that the chaincode execution time exceeded.

**Comment by andrew-coleman** [comment]
The gateway is telling you everything it knows.  It makes grpc calls to the other peers, and those calls exceed the timeout for reasons that it does not know.  It returns the DeadlineExceeded error code for each of those peers in the Details section of the error message.  I'm not sure what more we can add here.

**Comment by davidkel** [comment]
this might also be related to #292 however the message `context deadline exceeded` isn't very descriptive, if it's the endorseTimeout that has been exceeded then it would be more helpful to say that.

**Comment by bestbeforetoday** [comment]
I don't think there is anything more we can (or should) do with the client-side error messages to make this kind of situation easier to debug at the client end. It’s a server-side configuration or load/sizing issue that I would expect to be debugged and addressed at the server end using logging or other performance instrumentation. If the server-side logging is insufficient, please reopen.
