### ISSUE TITLE
Recommend Error Messages distinguish between gateway and returned from peer

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#279]
On Node If I have a problem with connection to a gateway from the client I get these messages
```
14 UNAVAILABLE: Connection dropped
1 CANCELLED: Call cancelled
```

I would be nice if these were qualified as coming from the gateway api as they look similar to errors returned by the gateway if the gateway had issues communicating with other nodes. 

Assume this would be the same for Java and Go clients as well.

**Comment by andrew-coleman** [comment]
If the error had originated from another node, then it would be included in the 'details' section of the error that is returned by the gateway.  If the 'details' array is empty, then the error would have originated in the gateway.
That's the theory anyway - let me know if you find one that doesn't follow that pattern.

Proposed docs: https://andrew-coleman-fabric.readthedocs.io/en/gateway_doc/gateway.html#errors

**Comment by davidkel** [comment]
@andrew-coleman In this case these errors originate from the client gateway, not the peer gateway I think it would be handy to be able to distinguish client side errors vs errors returned back by the gateway peer, useful for a support team for example

**Comment by bestbeforetoday** [comment]
The gRPC UNAVAILABLE status code indicates that the service is currently unavailable, and is most likely a transient condition that you may be able to retry. That should remain true whether the point of failure was the client connection to the Gateway peer, or some outage at the server end preventing the Gateway peer from invoking services on other nodes, so I think this behaviour is reasonable.

If you are seeing UNAVAILABLE returned for conditions where a retry would be inappropriate, or status codes other than UNAVAILABLE returned for conditions where a retry would be appropriate, that is a problem that should be fixed.

**Comment by bestbeforetoday** [comment]
Relates to this gRPC issue: grpc/grpc-go#3328
