### ISSUE TITLE
Recommendation for evaluate error message

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#282]
When attempting to evaluate where there are no available peers the following message is received
```
14 UNAVAILABLE: no endorsing peers found for chaincode basic in channel mychannel
```

Other error messages returned on an evaluate failure includes either `failed to evaluate transaction` or `evaluate call to endorser` so it would be good to be explicit in the message that it was for an evaluation request. The other thing is the term `found` and I wonder is this is the best choice of words given that it really means there are no peer available to perform the evaluation and that could be that the peers are unavailable or not got chaincode installed for example

**Comment by andrew-coleman** [comment]
How about `no peers available to evaluate chaincode basic in channel mychannel`?
