### ISSUE TITLE
Node timeouts are not distinguishable

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#294]
Now we have timeouts in our client for the various stages such as commit status, endorsing, evaluating etc following the pattern in the sample, I have seen the following error raised

```
4 DEADLINE_EXCEEDED: Deadline exceeded
```
Unfortunately the error doesn't say which timeout fired, just that something fired (And as usual the horrible grpc message is returned)

I can see this being a point of confusion for developers and support personnel when their client code throws this error. 
In our code we log each stage so we know that it actually occurred at the endorsing stage. But then we deliberately manage the stages of a submit ourselves, if a client application uses submitTransaction which bundles the stages together would they know which stage actually timed out ?

In our pattern logging is one solution, or we could try/catch around each stage as another to detect the individual timeout.

I don't know of the implications in the other sdks either

**Comment by bestbeforetoday** [comment]
Relates to issue #302 
Resolved by PR #304
