### ISSUE TITLE
Remove duplicate response payloads from EndorseResponse

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#316]
**As a** Gateway client implementer
**I want** no duplication of proposal response payload information in the Gateway's EndorseResponse
**So that** large response payloads do not fail due to gRPC message size limits

Proposal response is copied to the top level of the EndorseResponse for easy access. It can be accessed from within the transaction envelope so, while this means more work at the client end to extract, the top-level copy should be removed.

Proposal response payloads may be duplicated by the endorsing peer in both the response payload and chaincode action payloads. The Gateway peer should remove any duplication in the transaction message before returning to the Gateway client, and the client should use the remaining location to retrieve the transaction response.

I _think_ the correct response location is the chaincode action payload, and any other copies should be removed.

Tasks:

- [x] Client changes to use only chaincode action payload.
- [x] Gateway peer changes to remove top-level response and redundant response payload.
- [ ] Remove top-level response from EndorseResponse protobuf.

**Comment by denyeart** [comment]
Sounds right to me.
