### ISSUE TITLE
Update gateway contributing guide

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#324]
Tasks:

- [x] Refer to GitHub issues rather than Jira for reporting bugs or feature requests.
- [x] Refer to RocketChat, StackOverflow, Fabric mailing list and GitHub discussions for questions.
- [x] Point to any coding practices that might be relevant.
    - Effective Go
    - Use Go "errors" library, not third-party libraries
    - Effective Java
    - Changes include code, tests and documentation
- [x] Test requirements (unit and, where relevant, scenario tests), including testing frameworks that should be used.
    - Java: [AssertJ](https://assertj.github.io/doc/), [Mockito](https://site.mockito.org/)
    - Node: [Jest](https://jestjs.io/)
    - Go: [testify](https://github.com/stretchr/testify), [gomock](https://github.com/golang/mock)
    - Scenario tests: [Cucumber](https://cucumber.io/docs/installation/)
- [x] Relevant issue tags, for example: `help wanted`, `good first issue`.
- [x] Review process / expectations?

**Comment by denyeart** [comment]
@bestbeforetoday Do you envision updates to the Fabric ReadTheDocs contribution guide? Or something in fabric-gateway repo?

**Comment by bestbeforetoday** [comment]
> @bestbeforetoday Do you envision updates to the Fabric ReadTheDocs contribution guide? Or something in fabric-gateway repo?

A contributing guide specific to this repository. Rightly or wrongly, the ReadTheDocs content is entirely focused on core fabric. Even if other repositories like the fabric-gateway repo were mentioned there, there are repository specific information that makes sense to document in the repository.
