### ISSUE TITLE
Gateway doesn't balance endorsements across other Orgs

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-gateway#338]
With an initial setup of a 3 org network and an implicit majority endorsement policy and chaincode installed on all peers in all orgs I see that Org3 never endorses.

If I add a 4th org onto the network
Org4 endorses but Org3 never endorses

I change the endorsement policy to be org1,org2,org3 must endorse and Org3 starts endorsing (org4 stops endorsing)

I change the endorsement policy to be an explicit majority of 3 out of 4
```
OR(AND(Org1MSP.member,Org2MSP.member,Org3MSP.member),AND(Org1MSP.member,Org2MSP.member,Org4MSP.member),AND(Org1MSP.member,Org3MSP.member,Org4MSP.member),AND(Org2MSP.member,Org3MSP.member,Org4MSP.member))
```
and org4 does not endorse, only orgs 2 and 3

I change the endorsement policy to the same explicit majority but slightly different order now
```
"OR(AND('Org1MSP.member','Org2MSP.member','Org4MSP.member'),AND('Org1MSP.member','Org2MSP.member','Org3MSP.member'),AND('Org1MSP.member','Org3MSP.member','Org4MSP.member'),AND('Org2MSP.member','Org3MSP.member','Org4MSP.member'))
```
Org3 stops endorsing and Org4 starts endorsing

**Comment by andrew-coleman** [comment]
Resolved by https://github.com/hyperledger/fabric/pull/3089

**Comment by davidkel** [comment]
confirmed as fixed
