### ISSUE TITLE
Remove Go client dependency on Fabric protoutils

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#342]
`go.mod` contains:
> github.com/hyperledger/fabric v2.1.1+incompatible

This is used in `pkg/client/proposalbuilder.go` to build the proposal. The client could just build the proposal itself, as it does in the Node and Java implementations, and avoid any dependency on core Fabric.

**Comment by Anil8753** [comment]
I am getting the build issues if I use the fabric-sdk-go `gateway` along with the `fabric-gateway`

```
# github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client
vendor/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client/api.go:47:28: undefined: discovery.ChaincodeCall
vendor/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client/client.go:83:53: undefined: discovery.ChaincodeInterest
vendor/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client/client.go:120:55: undefined: discovery.ChaincodeCall
vendor/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client/client.go:124:13: undefined: discovery.ChaincodeInterest
vendor/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client/client.go:229:95: undefined: discovery.ChaincodeCall
vendor/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client/client.go:247:54: undefined: discovery.ChaincodeCall
vendor/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client/client.go:604:38: undefined: discovery.ChaincodeInterest
vendor/github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client/client.go:620:25: undefined: discovery.ChaincodeCall
```

**Comment by bestbeforetoday** [comment]
Thank you for the report. Do you think this issue is caused by the **fabric-gateway** client dependency on core fabric?

**Comment by andrew-coleman** [comment]
In the fabric-protos, the ChaincodeCall and ChaincodeInterest messages moved from discovery.proto into proposal_response.proto to avoid a cyclic dependency.  The protos remain compatible, but I guess because the code is being vendored into fabric-sdk-go, that will need updating.

**Comment by Anil8753** [comment]
> In the fabric-protos, the ChaincodeCall and ChaincodeInterest messages moved from discovery.proto into proposal_response.proto to avoid a cyclic dependency. The protos remain compatible, but I guess because the code is being vendored into fabric-sdk-go, that will need updating.

Would you be suggesting something to get rid of these errors?

**Comment by bestbeforetoday** [comment]
The dependency on `github.com/hyperledger/fabric v2.1.1+incompatible` is flagged as a potential security vulnerability, which raises the priority of its removal.

**Comment by MrHIDEn** [comment]
How to solve that issue? Please.
`# github.com/hyperledger/fabric-sdk-go/internal/github.com/hyperledger/fabric/discovery/client
C:\Users\mkrzy\go\pkg\mod\github.com\hyperledger\fabric-sdk-go@v1.0.0\internal\github.com\hyperledger\fabric\discovery\client\api.go:47:38: undefined: discovery.ChaincodeCall
C:\Users\mkrzy\go\pkg\mod\github.com\hyperledger\fabric-sdk-go@v1.0.0\internal\github.com\hyperledger\fabric\discovery\client\client.go:83:63: undefined: discovery.ChaincodeInterest
C:\Users\mkrzy\go\pkg\mod\github.com\hyperledger\fabric-sdk-go@v1.0.0\internal\github.com\hyperledger\fabric\discovery\client\client.go:120:65: undefined: discovery.ChaincodeCall
C:\Users\mkrzy\go\pkg\mod\github.com\hyperledger\fabric-sdk-go@v1.0.0\internal\github.com\hyperledger\fabric\discovery\client\client.go:124:23: undefined: discovery.ChaincodeInterest
C:\Users\mkrzy\go\pkg\mod\github.com\hyperledger\fabric-sdk-go@v1.0.0\internal\github.com\hyperledger\fabric\discovery\client\client.go:229:105: undefined: discovery.ChaincodeCall 
C:\Users\mkrzy\go\pkg\mod\github.com\hyperledger\fabric-sdk-go@v1.0.0\internal\github.com\hyperledger\fabric\discovery\client\client.go:247:64: undefined: discovery.ChaincodeCall  
C:\Users\mkrzy\go\pkg\mod\github.com\hyperledger\fabric-sdk-go@v1.0.0\internal\github.com\hyperledger\fabric\discovery\client\client.go:604:48: undefined: discovery.ChaincodeInterest
C:\Users\mkrzy\go\pkg\mod\github.com\hyperledger\fabric-sdk-go@v1.0.0\internal\github.com\hyperledger\fabric\discovery\client\client.go:620:35: undefined: discovery.ChaincodeCall `

**Comment by bestbeforetoday** [comment]
This is a [fabric-sdk-go](https://github.com/hyperledger/fabric-sdk-go/pull/208) issue so really should be reported in that repository, not here.  I made a change to fabric-sdk-go to try to resolve this in PR hyperledger/fabric-sdk-go#208. Unfortunately there has not been a release tagged since then. Maybe you can resolve it by depending on a [pseudo-version](https://go.dev/ref/mod#pseudo-versions) of fabric-sdk-go that includes that change.

Current releases of fabric-gateway no longer use [fabric-protos-go](https://github.com/hyperledger/fabric-protos-go) but instead uses [fabric-protos-go-apiv2](https://github.com/hyperledger/fabric-protos-go-apiv2), so there should be no Go module version contention between them. However, protobuf messages might be registered by the protobuf runtime in a global registry, which could cause [namespace conflicts](https://protobuf.dev/reference/go/faq/#namespace-conflict). This simplest resolution to that might be to switch an application entirely to fabric-gateway and avoid using it in combination with fabric-sdk-go.
