### ISSUE TITLE
Warning : The identity is a member of a different MSP 

### ISSUE THREAD

**Issue by sapthasurendran** [hyperledger/fabric-gateway#349]
Network setup: 
Started a 3 orgs 2 peers each.
Created the channel and deployed chaincode
gateway peer:peer.org1.example.com

Issue: 
Logs are  getting populated with warning messages while making successful transactions: 

`[discovery.acl] SatisfiesPrincipal -> identity does not satisfy principal error="the identity is a member of a different MSP (expected Org1MSP, got Org2MSP)" errorVerbose="the identity is a member of a different MSP (expected Org1MSP, got Org2MSP)\ngithub.com/hyperledger/fabric/msp.(*bccspmsp).satisfiesPrincipalInternalV142\n\t/go/src/github.com/hyperledger/fabric/msp/mspimpl.go:628\ngithub.com/hyperledger/fabric/msp.(*bccspmsp).SatisfiesPrincipal\n\t/go/src/github.com/hyperledger/fabric/msp/mspimpl.go:430\ngithub.com/hyperledger/fabric/msp/cache.(*cachedMSP).SatisfiesPrincipal\n\t/go/src/github.com/hyperledger/fabric/msp/cache/cache.go:123\ngithub.com/hyperledger/fabric/msp/cache.(*cachedIdentity).SatisfiesPrincipal\n\t/go/src/github.com/hyperledger/fabric/msp/cache/cache.go:58\ngithub.com/hyperledger/fabric/common/cauthdsl.compile.func2\n\t/go/src/github.com/hyperledger/fabric/common/cauthdsl/cauthdsl.go:77\ngithub.com/hyperledger/fabric/common/cauthdsl.compile.func1\n\t/go/src/github.com/hyperledger/fabric/common/cauthdsl/cauthdsl.go:47\ngithub.com/hyperledger/fabric/common/cauthdsl.(*policy).EvaluateIdentities\n\t/go/src/github.com/hyperledger/fabric/common/cauthdsl/policy.go:103\ngithub.com/hyperledger/fabric/common/cauthdsl.(*policy).EvaluateSignedData\n\t/go/src/github.com/hyperledger/fabric/common/cauthdsl/policy.go:93\ngithub.com/hyperledger/fabric/common/policies.(*PolicyLogger).EvaluateSignedData\n\t/go/src/github.com/hyperledger/fabric/common/policies/policy.go:286\ngithub.com/hyperledger/fabric/common/policies.(*ImplicitMetaPolicy).EvaluateSignedData\n\t/go/src/github.com/hyperledger/fabric/common/policies/implicitmeta.go:92\ngithub.com/hyperledger/fabric/common/policies.(*PolicyLogger).EvaluateSignedData\n\t/go/src/github.com/hyperledger/fabric/common/policies/policy.go:286\ngithub.com/hyperledger/fabric/internal/peer/gossip.(*MSPMessageCryptoService).VerifyByChannel\n\t/go/src/github.com/hyperledger/fabric/internal/peer/gossip/mcs.go:246\ngithub.com/hyperledger/fabric/internal/peer/gossip.(*MSPMessageCryptoService).Verify\n\t/go/src/github.com/hyperledger/fabric/internal/peer/gossip/mcs.go:222\ngithub.com/hyperledger/fabric/gossip/identity.(*identityMapperImpl).Verify\n\t/go/src/github.com/hyperledger/fabric/gossip/identity/identity.go:179\ngithub.com/hyperledger/fabric/gossip/gossip.(*Node).validateStateInfoMsg.func1\n\t/go/src/github.com/hyperledger/fabric/gossip/gossip/gossip_impl.go:1230\ngithub.com/hyperledger/fabric/gossip/protoext.(*SignedGossipMessage).Verify\n\t/go/src/github.com/hyperledger/fabric/gossip/protoext/signing.go:132\ngithub.com/hyperledger/fabric/gossip/gossip.(*Node).validateStateInfoMsg\n\t/go/src/github.com/hyperledger/fabric/gossip/gossip/gossip_impl.go:1236\ngithub.com/hyperledger/fabric/gossip/gossip.(*gossipAdapterImpl).ValidateStateInfoMessage\n\t/go/src/github.com/hyperledger/fabric/gossip/gossip/chanstate.go:180\ngithub.com/hyperledger/fabric/gossip/gossip/channel.(*gossipChannel).handleStateInfSnapshot\n\t/go/src/github.com/hyperledger/fabric/gossip/gossip/channel/channel.go:786\ngithub.com/hyperledger/fabric/gossip/gossip/channel.(*gossipChannel).HandleMessage\n\t/go/src/github.com/hyperledger/fabric/gossip/gossip/channel/channel.go:628\ngithub.com/hyperledger/fabric/gossip/gossip.(*Node).handleMessage\n\t/go/src/github.com/hyperledger/fabric/gossip/gossip/gossip_impl.go:372\ngithub.com/hyperledger/fabric/gossip/gossip.(*Node).acceptMessages\n\t/go/src/github.com/hyperledger/fabric/gossip/gossip/gossip_impl.go:326\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371" requiredPrincipal="principal:\"\\n\\007Org1MSP\\020\\003\" " identity="(mspid=Org2MSP subject=CN=peer0.org2.example.com,OU=peer,L=San Francisco,ST=California,C=US issuer=CN=ca.org2.example.com,O=org2.example.com,L=San Francisco,ST=California,C=US serialnumber=280541228011480321420417454954707362033)"`
[peer0.gateway.log](https://github.com/hyperledger/fabric-gateway/files/7692431/peer0.gateway.log)

**Comment by denyeart** [comment]
Fixed in Fabric v2.4.1.
