### ISSUE TITLE
Can't run the sample-network using “make sample-network” on Windows

### ISSUE THREAD

**Issue by YNZJ667** [hyperledger/fabric-gateway#354]
According to "https://github.com/hyperledger/fabric-gateway/tree/main/samples", I want to use the command "make sample-network” to run the sample network. But there are some problems to stop the test. The debug information tell me " Given I have deployed a Fabric network " and " fork/exec ./generate.sh: %1 is not a valid Win32 application". How can I solve the problem.
![image](https://user-images.githubusercontent.com/53722056/146636178-e9bd3049-eaf9-4574-99fc-17700fdc64fd.png)
![image](https://user-images.githubusercontent.com/53722056/146636185-b56e586f-2f25-40df-9ee8-37a2c58ff93a.png)

**Comment by jonmchan** [comment]
I don't believe the SDK has been tested or supported on Windows. 

https://github.com/hyperledger/fabric-gateway/blob/50615dd43f0dd24002aba0056ca5450cc4f1ec2e/scenario/fixtures/generate.sh would have to be converted to batch or powershell at minimum.

**Comment by bestbeforetoday** [comment]
The client API itself should work on Windows OK but, as is correctly pointed out above, the scenario tests in this repository are only tested/run on Linux as part of the automated build pipeline, and by contributors who tend to be using Linux (either natively or in a virtual machine within Windows) or MacOS.

For an end user sample that should run on Windows, you could try this:

https://hyperledger-fabric.readthedocs.io/en/latest/write_first_app.html

**Comment by bestbeforetoday** [comment]
The `make sample-network` target does run successfully for me on Windows using an Ubuntu 20.04 image running in Windows Subsystem for Linux 2. For a Windows system, that would be my recommended approach for contributing or running samples contained within this repository that rely on the scenario test framework. The main Fabric samples (linked above) should be runnable directly in Windows.
