### ISSUE TITLE
Naming Inconsistency - Network vs. Channel

### ISSUE THREAD

**Issue by jonmchan** [hyperledger/fabric-gateway#355]
I noticed an inconsistency between java, go, and the javascript code for the `network` and `channel` reference.

In node, the terminology is:

[`node/src/gateway.ts:`](https://github.com/hyperledger/fabric-gateway/blob/1e4a926ddb98ec8ee969da3fc1500642ab389d01/node/src/gateway.ts#L190)
```
getNetwork(channelName: string): Network;
```

in Java, it is:

[`java/src/main/java/org/hyperledger/fabric/client/Gateway.java:`](https://github.com/hyperledger/fabric-gateway/blob/1e4a926ddb98ec8ee969da3fc1500642ab389d01/java/src/main/java/org/hyperledger/fabric/client/GatewayImpl.java#L120)
```
Network getNetwork(String networkName);
```

in Go, it is:

[`pkg/client/gateway.go:`](https://github.com/hyperledger/fabric-gateway/blob/main/pkg/client/gateway.go#L158)

```
func (gw *Gateway) GetNetwork(name string) *Network 
```

As network is a very overloaded word in this context (blockchain networks and internet technology industry), I would propose to use the more exact term `Channel`.

I understand that according to the docs `[In Hyperledger Fabric], we’ll refer to both the “network” and the “channel”. In Hyperledger Fabric, these terms are effectively synonymous, as they both refer collectively to the organizations, components, policies, and processes that govern the interactions between organizations within a defined structure.` (https://hyperledger-fabric.readthedocs.io/en/latest/network/network.html#what-is-a-blockchain-network). 

However, I believe there may be an argument in code to keep it consistent, concise, and clear for ease of development. Utilizing the class name `Channel` and the functions as `getChannel` may help steer new developers from thinking these classes have more responsibilities than channel level responsibilities and would help be more in line with what I view as the technical architecture of hyperledger fabric.

**Comment by bestbeforetoday** [comment]
There was a decision several years ago on the naming in the Fabric programming model (in other words, the client APIs), to be more oriented more to business and general programming terminology rather than being tied to the technical terminology invented for the Fabric implementation. To move away from that now would be a breaking change for all the existing client APIs so this is not going to happen.

**Comment by jonmchan** [comment]
Sounds good.

If such, should node/src/gateway.ts: `getNetwork(channelName: string): Network;` be `getNetwork(networkName: string): Network;` for consistency?

**Comment by bestbeforetoday** [comment]
I wouldn’t mind a change like that, although I would probably just pick `getNetwork(name: string)` to avoid the repetition of **network**. This isn’t a change to the method signature; effectively just a documentation change.

**Comment by jonmchan** [comment]
@bestbeforetoday still struggling with the naming inconsistencies - going through the contract at this point, and note that it no longer is "network", but now `channelName`. If we don't have a Channel class, should a contract really have a `channelName` or should it have a `networkName`? 

I note this in all three implementations:

https://github.com/hyperledger/fabric-gateway/blob/1e4a926ddb98ec8ee969da3fc1500642ab389d01/pkg/client/contract.go#L31

https://github.com/hyperledger/fabric-gateway/blob/1e4a926ddb98ec8ee969da3fc1500642ab389d01/node/src/contract.ts#L202

https://github.com/hyperledger/fabric-gateway/blob/1e4a926ddb98ec8ee969da3fc1500642ab389d01/java/src/main/java/org/hyperledger/fabric/client/ContractImpl.java#L15

Just to give context, I'm fine using the library as-is, but in porting to ruby, I am trying to bring consistency and make sense of everything as I port. TIA.

**Comment by bestbeforetoday** [comment]
The naming of these private internal variables lines up more closely with the naming scheme of the protobuf fields that they are used to populate. If you are doing a Ruby implementation of the same API, you can choose whatever names (and code structure) make sense to you for the internal implementation. The protobuf field names cannot be changed.
