### ISSUE TITLE
Is Signed Data/Transaction possible ? 

### ISSUE THREAD

**Issue by karthiksukumaran** [hyperledger/fabric-gateway#474]
Hi All, I am creating multiple users in fabric network. The users will hold the private key. We don't want each user to connect to the node so we are creating a API through which the users can execute transaction.
But we don't want the users to pass the Private key, Is there a way the users can sign with their private key and send the signed data to Fabric Gateway API and it in turn does the transactions without passing the private key during the Gateway Initialization ?

**Comment by andrew-coleman** [comment]
Yes, all of the APIs support offline signing.  See https://pkg.go.dev/github.com/hyperledger/fabric-gateway/pkg/client#example-Contract-OfflineSign for an example.

Please ask usage questions on the mailing list or discord channel.  Github issues are for reporting bugs or tracking new development.  Thanks.
