### ISSUE TITLE
Support Node 18 LTS

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/fabric-gateway#483]
**As a** TypeScript / JavaScript application developer
**I want** to use Node 18 LTS
**So that** I can remain current with the latest Node features and security fixes

Node 18 is scheduled to become the active LTS release on 2022-10-25:

- https://github.com/nodejs/release#release-schedule

Tasks:

- [x] Add Node 18 to the test matrix in the CI pipeline.
- [x] Add Node 18 to the compatibility matrix in the documentation (gh-pages branch).

**Comment by vishwas031** [comment]
@bestbeforetoday I would like to work on this issue.
