### ISSUE TITLE
Cannot get transaction id and timestamp  

### ISSUE THREAD

**Issue by Burnaviour** [hyperledger/fabric-gateway#525]
Cannot get transaction id and timestamp of transaction using get history key function response there is no property txId and timestamp

**Comment by bestbeforetoday** [comment]
This should be reported to the appropriate chaincode project:

- [Node](https://github.com/hyperledger/fabric-chaincode-node)
- [Go](https://github.com/hyperledger/fabric-chaincode-go)
- [Java](https://github.com/hyperledger/fabric-chaincode-java)
