### ISSUE TITLE
Sign a transaction data via Wallet 

### ISSUE THREAD

**Issue by kameshpal** [hyperledger/fabric-gateway#551]
Hi team,

I have integrated azure key vault as a custom wallet to node.js client sdk. We understand that currently gateway transaction submit method will fetch private key from wallet and sign the data and transaction is submitted. So, we are exploring on opportunities to enable wallet to sign a transaction and submit the same. This helps us to restrict private key details with wallet itself. Could some help me in this regards?

Thanks in Advance,
Kamesh p 
 @azure key vault @nodejs

**Comment by bestbeforetoday** [comment]
Is this a question about how to make your Azure key vault integration work with the [fabric-network](https://www.npmjs.com/package/fabric-network) package or the [@hyperledger/fabric-gateway](https://www.npmjs.com/package/@hyperledger/fabric-gateway) package?

**Comment by bestbeforetoday** [comment]
No response so closing
