### ISSUE TITLE
error: no combination of peers can be derived which satisfy the endorsement policy

### ISSUE THREAD

**Issue by zRich** [hyperledger/fabric-gateway#604]
## EndorseError: 9 FAILED_PRECONDITION: no combination of peers can be derived which satisfy the endorsement policy

when running application-gateway-typescript on test-network. 

I am following the instructing of https://hyperledger-fabric.readthedocs.io/en/release-2.5/write_first_app.html on fabric 2.5.3

but facing problem when running npm start

![image](https://github.com/hyperledger/fabric-gateway/assets/2752413/7ad1f414-dffb-4f8b-9ac5-f0341bacf358)

**Comment by bestbeforetoday** [comment]
It looks like the chaincode was not deployed successfully prior to the client application being run.
