### ISSUE TITLE
Import fail in ES module format application

### ISSUE THREAD

**Issue by ksanjaykumar1** [hyperledger/fabric-gateway#662]
I want to use ''@hyperledger/fabric-gateway'' in my nodejs application which is in ES module format but it's not importing correctly I tried two hacks listed online to fix it but failed. 

 
![Screenshot from 2023-12-18 13-21-13](https://github.com/hyperledger/fabric-gateway/assets/72605368/0d3fe667-a4a3-41f6-9f95-c2ea0e72ec2a)

I imported as mentioned in the error message but it failed to import Contract and Identity.
![Screenshot from 2023-12-18 13-21-54](https://github.com/hyperledger/fabric-gateway/assets/72605368/2401b5a3-07aa-4755-8114-d5ae19afd0b7)

I set the format type as module in the fabric gateway library but it failed.  

![Screenshot from 2023-12-18 16-21-52](https://github.com/hyperledger/fabric-gateway/assets/72605368/6380aa24-a822-491a-8c79-5127e4df8412)

**Comment by bestbeforetoday** [comment]
[Contract](https://hyperledger.github.io/fabric-gateway/main/api/node/interfaces/Contract.html) (similar to many of the other types defined by `@hyperledger/fabric-gateway`) is an interface. It is just a TypeScript type definition to describe the behaviour of objects returned from [Network.getContract()](https://hyperledger.github.io/fabric-gateway/main/api/node/interfaces/Network.html#getContract). There is no concrete Contract class exported. If you are using TypeScript, you should be able to import all of those types OK and, based on those types, get code assistance in your IDE and compile-time validation from the TypeScript compiler. If you are writing plain JavaScript, you can ignore all the interface types and probably only need to import the [connect](https://hyperledger.github.io/fabric-gateway/main/api/node/functions/connect.html) function (and [signers](https://hyperledger.github.io/fabric-gateway/main/api/node/modules/signers.html) to use the [signers.newPrivateKeySigner](https://hyperledger.github.io/fabric-gateway/main/api/node/functions/signers.newPrivateKeySigner.html) function). The [API documentation](https://hyperledger.github.io/fabric-gateway/main/api/node/) indicates which types are concrete classes, interfaces and functions.

**Comment by ksanjaykumar1** [comment]
It works. Thank you.
