### ISSUE TITLE
Not able to receive the chaincode tx events, but receiving the block events when block created

### ISSUE THREAD

**Issue by srisaim249** [hyperledger/fabric-gateway#698]
Hi team, I am new to the block chain, built the basic network setup, through application   invoke and query are working but when trying to get the events from block chain i am not able to receive the TX event.

- Programming language and version.
    Golang,
   version : 1.22.1 ,  
    OS :  linux/amd64

- Fabric version used - 2.5

below is the code that i have tried to receive the events 

package main

import (
	"bytes"
	"context"
	"crypto/x509"
	"encoding/json"
	"fmt"
	"os"
	"os/signal"
	"path"
	"sync"
	"syscall"
	"time"

	"github.com/hyperledger/fabric-gateway/pkg/client"
	"github.com/hyperledger/fabric-gateway/pkg/identity"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
)

const (
	MSPID         = "Org1MSP"
	cryptoPath    = "../Asample/crypto-config/peerOrganizations/org1.example.com"
	certPath      = cryptoPath + "/users/User1@org1.example.com/msp/signcerts"
	keyPath       = cryptoPath + "/users/User1@org1.example.com/msp/keystore"
	tlsCertPath   = cryptoPath + "/peers/peer0.org1.example.com/tls/ca.crt"
	peerEndpoint  = "127.0.0.1:7051"
	gatewayPeer   = "peer0.org1.example.com"
	chaincodeName = "demoCC"
	channelName   = "demochannel"
	FunctionName  = "GetAllAssets"
)

var USER_INTERRUPTED = false

func init() {
	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		sig := <-sigs
		fmt.Println("init-user interrupted")
		fmt.Println(sig)
		USER_INTERRUPTED = true
	}()

}
func main() {
	// The gRPC client connection should be shared by all Gateway connections to this endpoint
	clientConnection := newGrpcConnection()
	defer clientConnection.Close()

	id := newIdentity()
	fmt.Println("identity name ----->>>>", id.MspID())
	sign := newSign()

	// Create a Gateway connection for a specific client identity
	gw, err := client.Connect(
		id,
		client.WithSign(sign),
		client.WithClientConnection(clientConnection),
		// // Default timeouts for different gRPC calls
		client.WithEvaluateTimeout(15*time.Minute),
		client.WithEndorseTimeout(20*time.Minute),
		client.WithSubmitTimeout(15*time.Minute),
		client.WithCommitStatusTimeout(10*time.Minute),
	)
	if err != nil {
		panic(err)
	}
	defer gw.Close()

	network := gw.GetNetwork(channelName)
	fmt.Println("network name is -->>>>>>>>>>>>>>>>>>", network.Name())

	// initLedger(contract)

	wg := sync.WaitGroup{}
	wg.Add(1)
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	go ReadEventsFromChaincodetx(ctx, network, &wg)

	// replayBlockEvents(ctx, network, 10000) -  working
	wg.Wait()

}

// newGrpcConnection creates a gRPC connection to the Gateway server.
func newGrpcConnection() *grpc.ClientConn {
	//reading the ca.crt file for connection
	certificatePEM, err := os.ReadFile(tlsCertPath)
	if err != nil {
		panic(fmt.Errorf("failed to read TLS certifcate file: %w", err))
	}

	certificate, err := identity.CertificateFromPEM(certificatePEM)
	if err != nil {
		panic(err)
	}

	certPool := x509.NewCertPool()
	certPool.AddCert(certificate)
	transportCredentials := credentials.NewClientTLSFromCert(certPool, gatewayPeer)

	connection, err := grpc.Dial(peerEndpoint, grpc.WithTransportCredentials(transportCredentials))
	if err != nil {
		panic(fmt.Errorf("failed to create gRPC connection: %w", err))
	}

	fmt.Println("grpc is connection successfull")
	return connection
}

// newIdentity creates a client identity for this Gateway connection using an X.509 certificate.
func newIdentity() *identity.X509Identity {
	//reading the signcerts pem file  inside the MSP folder of a user along with MSPID
	certificatePEM, err := readFirstFile(certPath)
	if err != nil {
		panic(fmt.Errorf("failed to read certificate file: %w", err))
	}

	certificate, err := identity.CertificateFromPEM(certificatePEM)
	if err != nil {
		panic(err)
	}

	id, err := identity.NewX509Identity(MSPID, certificate)
	if err != nil {
		panic(err)
	}

	return id
}

// newSign ...  creates a function that generates a digital signature from a message digest using a private key.
func newSign() identity.Sign {
	//reading the privatekey from the key store folder
	privateKeyPEM, err := readFirstFile(keyPath)
	if err != nil {
		panic(fmt.Errorf("failed to read private key file: %w", err))
	}

	privateKey, err := identity.PrivateKeyFromPEM(privateKeyPEM)
	if err != nil {
		panic(err)
	}

	sign, err := identity.NewPrivateKeySign(privateKey)
	if err != nil {
		panic(err)
	}

	return sign
}

func readFirstFile(dirPath string) ([]byte, error) {
	dir, err := os.Open(dirPath)
	if err != nil {
		return nil, err
	}

	fileNames, err := dir.Readdirnames(1)
	if err != nil {
		return nil, err
	}

	return os.ReadFile(path.Join(dirPath, fileNames[0]))
}

// Format JSON data
func formatJSON(data []byte) string {
	var prettyJSON bytes.Buffer
	if err := json.Indent(&prettyJSON, data, "", "  "); err != nil {
		panic(fmt.Errorf("failed to parse JSON: %w", err))
	}
	return prettyJSON.String()
}

// ReadEventsFromChaincodetx ...
func ReadEventsFromChaincodetx(ctx context.Context, network *client.Network, wg *sync.WaitGroup) error {
	defer wg.Done()
	chaincodeEvent, err := network.ChaincodeEvents(ctx, chaincodeName)
	if err != nil {
		fmt.Println("error while starting to listen to chaincode events")
		return err
	}

	fmt.Println("  network.name", network.Name())

	for {
		if USER_INTERRUPTED {
			fmt.Println("closing the reading events")
			break
		}
		select {

		case event := <-chaincodeEvent:
			fmt.Println("received chaincode  event ", event)
			asset := formatJSON(event.Payload)
			fmt.Printf("\n<-- Chaincode event received: %s - %s\n", event.EventName, asset)
		default:
			time.Sleep(2 * time.Second)
			fmt.Println("timeout waiting for event")
		}
	}
	return nil
}

// func replayBlockEvents(ctx context.Context, network *client.Network, endBlock uint64) {
// 	fmt.Println("\n*** Start block event replay")

// 	events, err := network.BlockEvents(ctx, client.WithStartBlock(0))
// 	if err != nil {
// 		panic(fmt.Errorf("failed to start block event listening: %w", err))
// 	}

// 	for {
// 		if USER_INTERRUPTED {
// 			break
// 		}
// 		select {
// 		case <-time.After(10 * time.Second):
// 			log.Println(errors.New("timeout waiting for event replay"))

// 		case event := <-events:
// 			fmt.Printf("date - event:%+v\n", event.Data)

// 			blockNumber := event.GetHeader().GetNumber()
// 			fmt.Printf("\n<-- Replayed block number %d\n", blockNumber)

// 			if blockNumber == endBlock {
// 				// Reached the block containing the last submitted transaction so return to stop listening for events
// 				return
// 			}
// 		}
// 	}
// }

calling the create asset in another main.go file 

If anything, required/ need to add or update plz let me know 
Any suggestion would be appreciated.

**Comment by bestbeforetoday** [comment]
The [asset-transfer-events](https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-events) sample is a working example of receiving and replaying chaincode events. Note that the accompanying smart contract explicitly emits events in its transaction function implementation. Chaincode events are only emitted when a transaction (that explicitly emits a chaincode event) is submitted and updates the ledger.

There is some information on chaincode events and how they should be used in the [full-stack-asset-transfer-guide](https://github.com/hyperledger/fabric-samples/blob/main/full-stack-asset-transfer-guide/docs/ApplicationDev/05-ChaincodeEvents.md) sample.

**Comment by bestbeforetoday** [comment]
The smart contract transaction function emits an event by calling `SetEvent()` on the [Stub](https://pkg.go.dev/github.com/hyperledger/fabric-chaincode-go/shim#ChaincodeStubInterface) obtained from the [Context](https://pkg.go.dev/github.com/hyperledger/fabric-contract-api-go@v1.2.2/contractapi#TransactionContext) passed in to the transaction function.

From the chaincode stub API documentation (linked above):

```go
// SetEvent allows the chaincode to set an event on the response to the
// proposal to be included as part of a transaction. The event will be
// available within the transaction in the committed block regardless of the
// validity of the transaction.
// Only a single event can be included in a transaction, and must originate
// from the outer-most invoked chaincode in chaincode-to-chaincode scenarios.
// The marshaled ChaincodeEvent will be available in the transaction's ChaincodeAction.events field.
SetEvent(name string, payload []byte) error
```
