### ISSUE TITLE
Add Support for .NET

### ISSUE THREAD

**Issue by Varorbc** [hyperledger/fabric-gateway#716]
**As a**  .NET Developer
**I want**  .NET client API for Hyperledger Fabric v2.4+

**Comment by andrew-coleman** [comment]
A .NET client is not on the roadmap for this project.
The Peer Gateway has a well defined gRPC/protobuf interface enabling developers to create their own language bindings, so please feel free to create one for your needs.  However, the maintainers of this repo would not be taking on its maintenance here.

**Comment by bestbeforetoday** [comment]
To build a native C# client, you will likely need to:

1. Build [C# bindings](https://protobuf.dev/getting-started/csharptutorial/) for the [Fabric protocol buffer messages](https://github.com/hyperledger/fabric-protos). The definitions for the gRPC services provided by the Gateway are defined [here](https://github.com/hyperledger/fabric-protos/blob/47d152056ac21648178a6bdd11d1d5f4949fbb9f/gateway/gateway.proto#L27-L58).
2. For building and sending endorse and evaluate requests, your references are:
    - [ProposalBuilder.java](https://github.com/hyperledger/fabric-gateway/blob/main/java/src/main/java/org/hyperledger/fabric/client/ProposalBuilder.java)
    - [TransactionContext.java](https://github.com/hyperledger/fabric-gateway/blob/main/java/src/main/java/org/hyperledger/fabric/client/TransactionContext.java)
    - [ProposalImpl.java](https://github.com/hyperledger/fabric-gateway/blob/main/java/src/main/java/org/hyperledger/fabric/client/ProposalImpl.java)
3. For sending submit requests using the message returned from endorse, your reference is:
    - [TransactionImpl.java](https://github.com/hyperledger/fabric-gateway/blob/main/java/src/main/java/org/hyperledger/fabric/client/TransactionImpl.java)
4. For subsequently checking commit status for a submitted transaction, your references are:
    - [SubmittedTransactionImpl.java](https://github.com/hyperledger/fabric-gateway/blob/main/java/src/main/java/org/hyperledger/fabric/client/SubmittedTransactionImpl.java)
    - [CommitImpl.java](https://github.com/hyperledger/fabric-gateway/blob/main/java/src/main/java/org/hyperledger/fabric/client/CommitImpl.java)
5. For retrieving chaincode events, your references are:
    - [ChaincodeEventsBuilder.java](https://github.com/hyperledger/fabric-gateway/blob/main/java/src/main/java/org/hyperledger/fabric/client/ChaincodeEventsBuilder.java)
    - [ChaincodeEventsRequestImpl.java](https://github.com/hyperledger/fabric-gateway/blob/main/java/src/main/java/org/hyperledger/fabric/client/ChaincodeEventsRequestImpl.java)

An alternative — perhaps simpler — approach you might want to consider is to build a Fabric client in one of the currently supported languages (Go, Node, Java), and then expose this functionality to your .NET clients as a RESTful service.

**Comment by bestbeforetoday** [comment]
The chaincode uses gRPC to communicate with the Fabric peer. You could implement your own smart contract API in C#. As the documentation page I linked says, "Smart contract APIs are available for Go, Node.js, and Java". There is no existing C# smart contract API so you would have to implement it yourself.

As mentioned in the [contributing document](https://github.com/hyperledger/fabric-gateway/blob/main/CONTRIBUTING.md), please do not use issues to ask questions. Use one of the resources for question mentioned in that document.
